name: dl_verano19
channels:
   - defaults
   - anaconda
   - conda-forge
dependencies:
   - python>=3.7
   - numpy
   - scipy
   - pandas
   - matplotlib
   - seaborn
   - jupyter
   - ipykernel
   - tqdm
   - nltk
   - scikit-learn
   - bayesian-optimization
   - pip:
     - tensorflow==2.0.0-beta1
     - tensorflow_probability
     - tensorflow-addons
